CREATE TABLE "site_blogs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "site_blogs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256),
	"content" text,
	"author_id" uuid,
	"status" varchar(256) DEFAULT 'draft',
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "site_blogs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "site_profiles" (
	"id" uuid PRIMARY KEY NOT NULL,
	"username" varchar(256) NOT NULL,
	"invite_code" varchar(10),
	"inviter_id" uuid,
	"inviter_skipped" boolean DEFAULT false,
	"avatar_url" varchar(256),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "site_profiles_invite_code_unique" UNIQUE("invite_code")
);
--> statement-breakpoint
ALTER TABLE "site_profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "site_blogs" ADD CONSTRAINT "site_blogs_author_id_site_profiles_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."site_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "site_profiles" ADD CONSTRAINT "site_profiles_id_users_id_fk" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "site_profiles" ADD CONSTRAINT "site_profiles_inviter_id_site_profiles_id_fk" FOREIGN KEY ("inviter_id") REFERENCES "public"."site_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "title_idx" ON "site_blogs" USING btree ("title");--> statement-breakpoint
CREATE INDEX "invite_code_idx" ON "site_profiles" USING btree ("invite_code");--> statement-breakpoint
CREATE INDEX "inviter_id_idx" ON "site_profiles" USING btree ("inviter_id");