
### 获取信号列表
POST http://localhost:3000/api/signals
Content-Type: application/json

{
  "page": 1,
  "filter": {
    "categoryCode": "kol"
  }
}



### 获取推特关注列表
POST http://localhost:3000/api/tweets
Content-Type: application/json

{
  "page": 1,
  "filter": {
    "followed": true
  }
}

### 获取信号标签统计
POST http://localhost:3000/api/signal-statistics
Content-Type: application/json

{
  "type": "announcement",
  "filter": {
  }
}

### 链上检查支付订单
POST http://localhost:3000/api/payment/check
Content-Type: application/json

{
  "paymentId": "70deebbc-5752-4a6c-a187-32f80ef7ba81"
}